language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip
            - cd-hit
            - mcl

env:
  - BLASTVER=2.9.0

install:
    - "wget http://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${BLASTVER}/ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-${BLASTVER}+-x64-linux.tar.gz"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-${BLASTVER}+/bin:$PATH"

script:
    - "noary --version"
    - "noary --help"
    - "noary --check dummy"
    - "noary dummy"
    - "noary |& grep 'Need at least 1'"

